# ==========================================
# ===           DEFAULT VALUES           ===
# ==========================================

server:
  profiles: development
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xyz
    password: xyz
    properties.mail.smtp:
      starttls:
        enable: true
        required: true
      auth: true
      connectiontimeout: 5000
      writetimeout: 5000
datasource:
  ds_dvdrental:
      url: jdbc:postgresql://localhost:5432/etrack?createDatabaseIfNotExist=true&autoReconnect=true
      driverClassName: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
      username: postgres
      password: postgres
      tomcat:
        maxActive: 377
        maxWait: 30000
        maxIdle: 233
        minIdle: 89
        timeBetweenEvictionRunsMillis: 34000
        minEvictableIdleTimeMillis: 55000
        initialSize: 34
        testOnBorrow: true
        validationQuery: SELECT 1
        validationInterval: 34000
        removeAbandoned: true
        removeAbandonedTimeout: 55


